### ISSUE TITLE
Clarification required regarding multiple Users & Agents

### ISSUE THREAD

**Issue by TheArhaam** [decentralised-dataexchange/aries-mobileagent-flutter#1]
So I was going over the code and saw that you guys are using the agent running on"https://d4l-admin.igrant.io/api/doc", so since this is a single agent, won't there be a conflict for multiple users? One wallet is assigned to one agent if I'm not mistaken, wouldn't multiple users that login have access to the same wallet then?

Also, I tried to go through the demo flow but turns out I need an OTP, was wondering if maybe someone could help me out with that or maybe add the registration code?

Thank you 😄

**Comment by darkchylde** [comment]
@TheArhaam The codebase is outdated. The repo will be updated soon.
